projects/blog/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('article/<int:article_id>/', views.detail, name='detail'),
    path('article/<int:article_id>/add_comment/', views.add_comment, name='add_comment'),
]

projects/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

projects/blog/articles/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.


class Article(models.Model):
    article_title = models.CharField('Article title', max_length=100)
    article_text = models.TextField('Article text')
    published_date = models.DateTimeField('Article published date')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.published_date >= (timezone.now() - datetime.timedelta(days=7))


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Author name', max_length=50)
    comment_text = models.CharField('Comment text', max_length=200)

    def __str__(self):
        return self.author_name

projects/blog/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['article_title', 'article_text']

projects/blog/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Article, Comment
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from .forms import ArticleForm
from django.utils import timezone

# Create your views here.


def index(request):
    latest_articles_list = Article.objects.order_by('-published_date')
    form = ArticleForm()
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            Article.objects.create(article_text=form.cleaned_data['article_text'],
                                   article_title=form.cleaned_data['article_title'],
                                   published_date=timezone.now())
            # return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list, 'form': form})
            return redirect('articles:index')
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list, 'form': form})


def detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    articles = Article.objects.filter(id=article_id)
    return render(request, 'articles/detail.html', {'article': article, 'articles': articles})


def add_comment(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])
    return render(request, 'articles/detail.html', {'article': article})

projects/blog/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %}{{ article.article_title }}{% endblock %}
{% block content %}
    <div class="detail">
        <h2>{{ article.article_title }}</h2>
        <i>{{ article.published_date }}</i>
        <p>{{ article.article_text }}</p>
    </div>
    {% for article in articles %}
        {{ article.article_text }}
    {% endfor %}
    <hr/>
    <form action="{% url 'articles:add_comment' article.id %}" method="post">
    {%  csrf_token %}
        <input type="text" required placeholder="Enter your name" name="name">
        <br>
        <textarea type="text" required placeholder="Enter your comment" name="text"></textarea>
        <br>
        <button type="submit">Add comment</button>
    </form>
{%  endblock %}

projects/blog/articles/templates/articles/list.html
{%  extends 'base.html' %}
{% block title %}Last articles{% endblock %}

{% block content %}
    {% if latest_articles_list %}
        {% for article in latest_articles_list %}
            <div class="article">
                <i>{{ article.published_date }}</i>
            <a href="{% url 'articles:detail' article.id %}"><h3>{{ article.article_title }}</h3></a>
            <p>{{ article.article_text }}</p>
            <hr>
            </div>
        {% endfor %}
    {% endif %}
    <br>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

projects/blog/articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>